// Generated by npm run localization:types. Do not edit manually.
import 'i18next';
declare module 'i18next' {
    interface CustomTypeOptions {
        defaultNS: 'global/common';
        enableSelector: false;
        strictKeyChecks: true;
        resources: {
            'backend/about': typeof import('../../locales/backend/en/about.json');
            'backend/auth': typeof import('../../locales/backend/en/auth.json');
            'backend/dashboard': typeof import('../../locales/backend/en/dashboard.json');
            'backend/imports': typeof import('../../locales/backend/en/imports.json');
            'backend/moderation': typeof import('../../locales/backend/en/moderation.json');
            'backend/notifications': typeof import('../../locales/backend/en/notifications.json');
            'backend/parking-municipal': typeof import('../../locales/backend/en/parking-municipal.json');
            'backend/parking-offstreet': typeof import('../../locales/backend/en/parking-offstreet.json');
            'backend/parking-rules': typeof import('../../locales/backend/en/parking-rules.json');
            'backend/parking/confirmations': typeof import('../../locales/backend/en/parking/confirmations.json');
            'backend/parking/main': typeof import('../../locales/backend/en/parking/main.json');
            'backend/parking/trash': typeof import('../../locales/backend/en/parking/trash.json');
            'backend/profile': typeof import('../../locales/backend/en/profile.json');
            'backend/roles': typeof import('../../locales/backend/en/roles.json');
            'backend/security': typeof import('../../locales/backend/en/security.json');
            'backend/settings': typeof import('../../locales/backend/en/settings.json');
            'backend/sidebar': typeof import('../../locales/backend/en/sidebar.json');
            'backend/users': typeof import('../../locales/backend/en/users.json');
            'frontend/about': typeof import('../../locales/frontend/en/about.json');
            'frontend/contact': typeof import('../../locales/frontend/en/contact.json');
            'frontend/footer': typeof import('../../locales/frontend/en/footer.json');
            'frontend/garages': typeof import('../../locales/frontend/en/garages.json');
            'frontend/global': typeof import('../../locales/frontend/en/global.json');
            'frontend/home': typeof import('../../locales/frontend/en/home.json');
            'frontend/map/contribute': typeof import('../../locales/frontend/en/map/contribute.json');
            'frontend/map/favorites': typeof import('../../locales/frontend/en/map/favorites.json');
            'frontend/map/main': typeof import('../../locales/frontend/en/map/main.json');
            'frontend/map/modals': typeof import('../../locales/frontend/en/map/modals.json');
            'frontend/navbar': typeof import('../../locales/frontend/en/navbar.json');
            'global/common': typeof import('../../locales/global/en/common.json');
            'global/notification': typeof import('../../locales/global/en/notification.json');
            'global/search': typeof import('../../locales/global/en/search.json');
        };
    }
}
